#!/bin/bash

b=$(tput bold)
n=$(tput sgr0)
un=$(tput smul)
nun=$(tput rmul)

echo "${b}Container:${n} $1"
echo "${b}FROM:${n}      $2"
echo "${b}TO:${n}        $3"

echo "$coingecko_EA"

echo "${b}$2 / $3 --> ${n}"  $(curl -s --header "Content-Type: application/json" --request POST --data "{\"data\":{\"from\":\"$2\", \"to\":\"$3\"}}" $1 | jq -r .result)
