#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name alongside-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.249 \
 -p 2249:2249 \
 -e EA_PORT=2249 \
 -e TIMEOUT=60000 \
 -e API_ENDPOINT=$ALONGSIDE_API_ENDPOINT \
 -e ACCESS_KEY=$ALONGSIDE_ACCESS_KEY \
 -e PASSPHRASE=$ALONGSIDE_PASSPHRASE \
 -e PORTFOLIO_ID=$ALONGSIDE_PORTFOLIO_ID \
 -e SIGNING_KEY=$ALONGSIDE_SIGNING_KEY \
 -e RPC_URL=$POLYGON_RPC_URL \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=alongside \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e RATE_LIMIT_API_PROVIDER=alongside \
 -e RATE_LIMIT_API_TIER=$ALONGSIDE_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=alongside \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="alongside-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/alongside-adapter:$1
