#!/bin/bash

# ea-name: apy-finance-multi-redis
# endpoint: http://192.168.0.135:1135

source api_keys
source misc_vars

docker run \
 --name apy-finance-multi-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.0.135 \
 -p 1135:1135 \
 -e EA_PORT=1135 \
 -e NOMICS_ADAPTER_URL=http://192.168.1.111:1111 \
 -e CRYPTOCOMPARE_ADAPTER_URL=http://192.168.1.114:1114 \
 -e COINMARKETCAP_ADAPTER_URL=http://192.168.1.115:1115 \
 -e DEFAULT_QUOTE=USD \
 -e DEFAULT_METHOD=price \
 -e RPC_URL=$RPC_URL \
 -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
 -e REGISTRY_ADDRESS=0x7ec81b7035e91f8435bdeb2787dcbd51116ad303 \
 -e TIMEOUT=30000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=apy-finance-ethereum \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_REDIS_TIMEOUT=30000 \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=apyFinance-ethereum \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="apy-finance-multi-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/apy-finance-adapter:$1
