#!/bin/bash

# ea-name: bankfrick-redis
# endpoint: http://192.168.1.231

source api_keys
source misc_vars

docker run \
 --name bankfrick-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.231 \
 -p 2231:2231 \
 -e EA_PORT=2231 \
 -e TIMEOUT=30000 \
 -e API_KEY=$BANKFRICK_API_KEY \
 -e PRIVATE_KEY="$BANKFRICK_PRIVATE_KEY" \
 -e PAGE_SIZE=$BANKFRICK_PAGE_SIZE \
 -e API_ENDPOINT=$BANKFRICK_API_ENDPOINT \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=bankfrick \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=false \
 -e WARMUP_ENABLED=false \
 -e RATE_LIMIT_API_PROVIDER=bank-frick \
 -e RATE_LIMIT_API_TIER=$BANKFRICK_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=bankfrick \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="bankfrick-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/bank-frick-adapter:$1
