#!/bin/bash

# ea-name: cfbenchmarks-redis
# endpoint: http://192.168.1.168:1168

source api_keys
source misc_vars

docker run \
 --name cfbenchmarks-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.168 \
 -p 1168:1168 \
 -e EA_PORT=1168 \
 -e API_USERNAME=$CFBENCHMARKS_API_USERNAME \
 -e API_PASSWORD=$CFBENCHMARKS_API_PASSWORD \
 -e API_SECONDARY=false \
 -e TIMEOUT=30000 \
 -e CACHE_ENABLED=false \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=cfbenchmarks \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e WS_ENABLED=true \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=cfbenchmarks \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="cfbenchmarks-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/cfbenchmarks-adapter:$1
