#!/bin/bash

# ea-name: coinpaprika-state-redis
# endpoint: http://192.168.2.87:2087

source api_keys
source misc_vars

docker run \
 --name coinpaprika-state-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.87 \
 -p 2087:2087 \
 -e EA_PORT=2087 \
 -e TIMEOUT=30000 \
 -e API_KEY=$COINPAPRIKA_API_KEY \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_REDIS_MAX_QUEUED_ITEMS=2000 \
 -e CACHE_KEY_GROUP=coinpaprika-state \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_REDIS_TIMEOUT=5000 \
 -e CACHE_MIN_AGE=120000 \
 -e CACHE_MAX_AGE=180000 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=false \
 -e WS_ENABLED=false \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e RETRY=1 \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=coinpaprika-state \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="coinpaprika-state-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/coinpaprika-state-adapter:$1
