#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name coinbase-prime-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.30 \
 -p 2030:2030 \
 -e EA_PORT=2030 \
 -e TIMEOUT=60000 \
 -e ACCESS_KEY=$COINBASE_PRIME_ACCESS_KEY \
 -e PASSPHRASE=$COINBASE_PRIME_PASSPHRASE \
 -e SIGNING_KEY=$COINBASE_PRIME_SIGNING_KEY \
 -e ETH_ACCESS_KEY=$COINBASE_PRIME_ETH_ACCESS_KEY \
 -e ETH_PASSPHRASE=$COINBASE_PRIME_ETH_PASSPHRASE \
 -e ETH_SIGNING_KEY=$COINBASE_PRIME_ETH_SIGNING_KEY \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=coinbase-prime \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=coinbase-prime \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="coinbase-prime-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/coinbase-prime-adapter:$1
