#!/bin/bash

source ../api_keys
source ../misc_vars

docker run \
--name coinranking-redis \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.154 \
-p 1154:1154 \
-e EA_PORT=1154
-e TIMEOUT=30000 \
-e CACHE_ENABLED=true \
-e API_KEY=$COINRANKING_API_KEY \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=coinranking \
-e CACHE_KEY_IGNORED_PROPS=meta \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e EXPERIMENTAL_RATE_LIMIT_ENABLED=true \
-e EXPERIMENTAL_WARMUP_ENABLED=true \
-e RATE_LIMIT_API_TIER=pro \
-e REQUEST_COALESCING_ENABLED=true \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=true \
-e METRICS_NAME=coinranking \
-d public.ecr.aws/chainlink/adapters/coinranking-adapter:$1
