#!/bin/bash

source api_keys
source misc_vars

docker run \
--name currencylayer-redis \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.141 \
-p 1141:1141 \
-e EA_PORT=1141 \
-e API_KEY=$CURRENCYLAYER_API_KEY \
-e TIMEOUT=30000 \
-e CACHE_ENABLED=true \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=currencylayer \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e CACHE_REDIS_TIMEOUT=30000 \
-e REQUEST_COALESCING_ENABLED=false \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=true \
-e METRICS_NAME=currencylayer \
-d public.ecr.aws/chainlink/adapters/currencylayer-adapter:$1
