#!/bin/bash

# Source configuration files with absolute paths to ensure they work regardless of where the script is called from
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

source "${repo_root}/api_keys"
source "${repo_root}/misc_vars"
docker run \
 --name dar-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.244 \
 -p 2244:2244 \
 -e EA_PORT=2244 \
 -e TIMEOUT=60000 \
 -e API_USERNAME=$DAR_API_USERNAME \
 -e API_KEY=$DAR_API_KEY \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=dar \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e RATE_LIMIT_API_PROVIDER=dar \
 -e RATE_LIMIT_API_TIER=$DAR_HTTP_SUB \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=dar \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="dar-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/dar-adapter:$1
