#!/bin/bash

# ea-name: dxfeed
# endpoint: http://192.168.1.101:8001

source api_keys
source misc_vars

docker run -it \
 --name dxfeed \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.101 \
 -p 8001:8001 \
 -e EA_PORT=8001 \
 -e API_ENDPOINT=$DXFEED_API_ENDPOINT \
 -e API_USERNAME=$DXFEED_API_USERNAME \
 -e API_PASSWORD=$DXFEED_API_PASSWORD \
 -e WS_API_ENDPOINT=$DXFEED_WS_API_ENDPOINT \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=dxfeed \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="dxfeed" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/dxfeed-adapter:$1
