#!/bin/bash

source api_keys
source misc_vars

docker run -it \
--name dxfeed-secondary-redis \
--restart=unless-stopped \
--net eas-net \
--ip 192.168.1.100 \
-p 8000:8000 \
-e EA_PORT=8001 \
-e API_ENDPOINT=$DXFEED_API_ENDPOINT \
-e API_USERNAME=$DXFEED_API_USERNAME \
-e API_PASSWORD=$DXFEED_API_PASSWORD \
-d public.ecr.aws/chainlink/adapters/dxfeed-secondary-adapter:$1
