#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name dydx-staging-no-redis \
 --restart=unless-stopped \
 --ip 192.168.1.240 \
 -p 2240:8080 \
 -e TIMEOUT=60000 \
 -e PRIVATE_KEY=$DYDX_PRIVATE_KEY \
 -e STARK_MESSAGE=$DYDX_STARK_MESSAGE \
 -e ORACLE_NAME=$DYDX_ORACLE_NAME \
 -e API_ENDPOINT=$DYDX_STAGING_API_ENDPOINT \
 -e CACHE_ENABLED=false \
 -e RATE_LIMIT_ENABLED=false \
 -e WARMUP_ENABLED=false \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e RETRY=1 \
 -d dextrac/dydx-stark-adapter:$1
