#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name dydx-prod-no-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.239 \
 -p 2239:8080 \
 -e TIMEOUT=60000 \
 -e PRIVATE_KEY=$DYDX_PRIVATE_KEY \
 -e STARK_MESSAGE=$DYDX_STARK_MESSAGE \
 -e ORACLE_NAME=$DYDX_ORACLE_NAME \
 -e API_ENDPOINT=$DYDX_PROD_API_ENDPOINT \
 -e CACHE_ENABLED=false \
 -e RATE_LIMIT_ENABLED=false \
 -e WARMUP_ENABLED=false \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=dydx-prod \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="dydx-prod" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d dextrac/dydx-stark-adapter:$1
