#!/bin/bash

source api_keys
source misc_keys

docker run \
--name eodhistoricaldata-redis \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.132 \
-p 1132:1132 \
-e EA_PORT=1132 \
-e API_KEY=$EODHISTORICALDATA_API_KEY \
-e TIMEOUT=30000 \
-e CACHE_ENABLED=true \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=eodhistoricaldata \
-e CACHE_KEY_IGNORED_PROPS=meta \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e EXPERIMENTAL_RATE_LIMIT_ENABLED=true \
-e EXPERIMENTAL_WARMUP_ENABLED=true \
-e RATE_LIMIT_API_TIER=$EODHISTORICALDATA_SUB_HTTP \
-e REQUEST_COALESCING_ENABLED=true \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=true \
-e METRICS_NAME=eodhistoricaldata \
-d public.ecr.aws/chainlink/adapters/eodhistoricaldata-adapter:$1
