#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name eth-beacon-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.254 \
 -p 2254:2254 \
 -e EA_PORT=2254 \
 -e ETH_CONSENSUS_RPC_URL=$ETHEREUM_CONSENSUS_RPC_URL \
 -e ETH_EXECUTION_RPC_URL=$ETHEREUM_BEACON_RPC_URL \
 -e MAX_PAYLOAD_SIZE_LIMIT=2000000 \
 -e BATCH_SIZE=15 \
 -e TIMEOUT=60000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=eth-beacon \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=eth-beacon \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="eth-beacon-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/eth-beacon-adapter:$1
