#!/bin/bash

# Source configuration files with absolute paths to ensure they work regardless of where the script is called from
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

source "${repo_root}/api_keys"
source "${repo_root}/misc_vars"
docker run \
 --name eth-balance-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.48 \
 -p 2048:2048 \
 -e EA_PORT=2048 \
 -e ETHEREUM_CHAIN_ID=$ETHEREUM_CHAIN_ID \
 -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
 -e TIMEOUT=60000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=eth-balance \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=eth-balance \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="eth-balance-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/eth-balance-adapter:$1
