#!/bin/bash

# Source configuration files with absolute paths to ensure they work regardless of where the script is called from
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

source "${repo_root}/api_keys"
source "${repo_root}/misc_vars"
docker run \
 --name finalto-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.49 \
 -p 2049:2049 \
 -e EA_PORT=2049 \
 -e TIMEOUT=60000 \
 -e WS_API_USERNAME=$FINALTO_WS_API_USERNAME \
 -e WS_API_PASSWORD=$FINALTO_WS_API_PASSWORD \
 -e WS_API_ENDPOINT=$FINALTO_WS_API_ENDPOINT \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=finalto \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e RATE_LIMIT_API_PROVIDER=finalto \
 -e RATE_LIMIT_API_TIER=$finalto_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=finalto \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="finalto-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/finalto-adapter:$1
