#!/bin/bash

# Source configuration files with absolute paths to ensure they work regardless of where the script is called from
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

source "${repo_root}/api_keys"
source "${repo_root}/misc_vars"
docker run \
 --name galaxis-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.234 \
 -p 2234:2234 \
 -e EA_PORT=2234 \
 -e POLYGON_RPC_URL=$POLYGON_RPC_URL \
 -e TIMEOUT=60000 \
 -e API_ENDPOINT=$GALAXIS_API_ENDPOINT \
 -e EC_REGISTRY_ADDRESS=$GALAXIS_EC_REGISTRY_ADDRESS \
 -e EC_REGISTRY_MAP_ADDRESS=$GALAXIS_EC_REGISTRY_MAP_ADDRESS \
 -e CHAIN_BATCH_WRITE_ADAPTER_ADDRESS=$GALAXIS_CHAIN_BATCH_WRITE_ADAPTER_ADDRESS \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=galaxis \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e RATE_LIMIT_API_PROVIDER=galaxis \
 -e RATE_LIMIT_API_TIER=$GALAXIS_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=galaxis \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="galaxis-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/galaxis-adapter:$1
