#!/bin/bash

# ea-name: generic-api-unitas-nav-redis
# endpoint: http://192.168.2.107:2107

source api_keys
source misc_vars

docker run \
 --name generic-api-unitas-nav-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.107 \
 -p 2107:2107 \
 -e EA_PORT=2107 \
 -e TIMEOUT=30000 \
 -e CACHE_PREFIX=unitas-nav \
 -e ACCOUNTABLE_OPENDELTA_API_URL= \
 -e ACCOUNTABLE_OPENDELTA_AUTH_HEADER=Authorization \
 -e ACCOUNTABLE_UNITAS_NAV_API_URL= \
 -e ACCOUNTABLE_UNITAS_NAV_AUTH_HEADER=Authorization \
 -e ACCOUNTABLE_SOLSTICE_API_URL= \
 -e ACCOUNTABLE_SOLSTICE_AUTH_HEADER=Authorization \
 -e ACCOUNTABLE_OPENDELTA_AUTH_HEADER_VALUE=$ACCOUNTABLE_OPENDELTA_AUTH_HEADER_VALUE \
 -e ACCOUNTABLE_UNITAS_NAV_AUTH_HEADER_VALUE=$ACCOUNTABLE_UNITAS_NAV_AUTH_HEADER_VALUE \
 -e ACCOUNTABLE_SOLSTICE_AUTH_HEADER_VALUE=$ACCOUNTABLE_SOLSTICE_AUTH_HEADER_VALUE \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_REDIS_MAX_QUEUED_ITEMS=2000 \
 -e CACHE_KEY_GROUP=generic-api \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_REDIS_TIMEOUT=5000 \
 -e CACHE_MIN_AGE=120000 \
 -e CACHE_MAX_AGE=180000 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=false \
 -e WS_ENABLED=false \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e RETRY=1 \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=generic-api \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="generic-api-unitas-nav-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/generic-api-adapter:$1
