#!/bin/bash

# ea-name: gmx-tokens-redis
# endpoint: http://192.168.2.103:2103

source api_keys
source misc_vars

docker run \
 --name gmx-tokens-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.103 \
 -p 2103:2103 \
 -e EA_PORT=2103 \
 -e TIMEOUT=30000 \
 -e AVALANCHE_RPC_URL=$AVALANCHE_RPC_URL \
 -e DATA_ENGINE_ADAPTER_URL=http://192.168.2.88:2088 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=local \
 -e CACHE_MIN_AGE=120000 \
 -e CACHE_MAX_AGE=180000 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=false \
 -e WS_ENABLED=false \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=debug \
 -e DEBUG=true \
 -e RETRY=1 \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=gmx-tokens \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="gmx-tokens-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/gmx-tokens-adapter:$1
