#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name gsr-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.230 \
 -p 2230:2230 \
 -e EA_PORT=2230 \
 -e TIMEOUT=30000 \
 -e API_ENDPOINT=$GSR_API_ENDPOINT \
 -e WS_API_ENDPOINT=$GSR_WS_API_ENDPOINT \
 -e WS_USER_ID=$GSR_WS_USER_ID \
 -e WS_PUBLIC_KEY=$GSR_WS_PULIC_KEY \
 -e WS_PRIVATE_KEY=$GSR_WS_PRIVATE_KEY \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=gsr \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e RATE_LIMIT_API_PROVIDER=gsr \
 -e RATE_LIMIT_API_TIER=$GSR_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=gsr \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="gsr-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/gsr-adapter:$1
