#!/bin/bash

# ea-name: ice-redis
# endpoint: http://192.168.2.93:2093

source api_keys
source misc_vars

docker run \
 --name ice-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.93 \
 -p 2093:2093 \
 -e EA_PORT=2093 \
 -e TIMEOUT=30000 \
 -e NETDANIA_PASSWORD=$ICE_NETDANIA_PASSWORD \
 -e API_ENDPOINT=$ICE_API_ENDPOINT \
 -e API_ENDPOINT_FAILOVER_1=$ICE_API_ENDPOINT_FAILOVER_1 \
 -e API_ENDPOINT_FAILOVER_2=$ICE_API_ENDPOINT_FAILOVER_2 \
 -e API_ENDPOINT_FAILOVER_3=$ICE_API_ENDPOINT_FAILOVER_3 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_REDIS_MAX_QUEUED_ITEMS=2000 \
 -e CACHE_KEY_GROUP=ice \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_REDIS_TIMEOUT=5000 \
 -e CACHE_MIN_AGE=120000 \
 -e CACHE_MAX_AGE=180000 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=false \
 -e WS_ENABLED=true \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e RETRY=1 \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=ice \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="ice-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/ice-adapter:$1
