#!/bin/bash

source api_keys
source misc_vars

docker run \
--name iex-cloud-redis \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.102 \
-p 8002:8002 \
-e EA_PORT=8002 \
-e API_KEY=$IEXCLOUD_API_KEY \
-e TIMEOUT=30000 \
-e CACHE_ENABLED=true \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=iex-cloud \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e CACHE_REDIS_TIMEOUT=30000 \
-e RATE_LIMIT_ENABLED=true \
-e WARMUP_ENABLED=true \
-e RATE_LIMIT_API_PROVIDER=iexcloud \
-e RATE_LIMIT_API_TIER=$IEX_CLOUD_SUB_HTTP \
-e REQUEST_COALESCING_ENABLED=false \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=true \
-e METRICS_NAME=iexcloud \
-d public.ecr.aws/chainlink/adapters/iex-cloud-adapter:$1
