#!/bin/bash

source api_keys
source misc_vars


docker run \
 --name implied-price-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.174 \
 -p 1174:1174 \
 -e EA_PORT=1174 \
 -e COINGECKO_ADAPTER_URL=http://192.168.1.113:1113 \
 -e COINMARKETCAP_ADAPTER_URL=http://192.168.1.115:1115 \
 -e COINPAPRIKA_ADAPTER_URL=http://192.168.1.116:1116 \
 -e CRYPTOCOMPARE_ADAPTER_URL=http://192.168.1.114:1114 \
 -e NOMICS_ADAPTER_URL=http://192.168.1.111:1111 \
 -e TIINGO_ADAPTER_URL=http://192.168.1.134:1134 \
 -e TIMEOUT=30000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=implied-price \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=implied-price \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="implied-price-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/implied-price-adapter:$1
