#!/bin/bash

# ea-name: itick-redis
# endpoint: http://192.168.2.115:2115

source api_keys
source misc_vars

docker run \
 --name itick-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.115 \
 -p 2115:2115 \
 -e EA_PORT=2115 \
 -e API_KEY_CN=$ITICK_API_KEY_CN \
 -e API_KEY_GB=$ITICK_API_KEY_GB \
 -e API_KEY_HK=$ITICK_API_KEY_HK \
 -e API_KEY_JP=$ITICK_API_KEY_JP \
 -e API_KEY_KR=$ITICK_API_KEY_KR \
 -e API_KEY_TW=$ITICK_API_KEY_TW \
 -e TIMEOUT=30000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=itick \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_REDIS_TIMEOUT=10000 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=itick \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="itick-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/itick-adapter:$1
