#!/bin/bash

# ea-name: jpegd-redis
# endpoint: http://192.168.1.171:1171

source api_keys
source misc_vars

docker run \
 --name jpegd-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.171 \
 -p 1171:1171 \
 -e EA_PORT=1171 \
 -e TIMEOUT=30000 \
 -e API_KEY=$JPEGD_API_KEY \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=jpegd \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=false \
 -e WARMUP_ENABLED=falst \
 -e RATE_LIMIT_API_PROVIDER=jpegd \
 -e RATE_LIMIT_API_TIER=$JPEGD_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=jpegd \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="jpegd-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/jpegd-adapter:$1
