#!/bin/bash

# ea-name: layer2-sequencer-health-redis
# endpoint: http://192.168.1.220:1220

source api_keys
source misc_vars

docker run \
 --name layer2-sequencer-health-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.220 \
 -p 1220:1220 \
 -e EA_PORT=1220 \
 -e ARBITRUM_RPC_ENDPOINT=$ARBITRUM_RPC_URL \
 -e BASE_RPC_ENDPOINT=$BASE_RPC_URL \
 -e CELO_RPC_ENDPOINT=$CELO_RPC_URL \
 -e INK_RPC_ENDPOINT=$INK_RPC_URL \
 -e MANTLE_RPC_ENDPOINT=$MANTLE_RPC_URL \
 -e METIS_HEALTH_ENDPOINT=https://andromeda-healthy.metisdevops.link/health \
 -e METIS_RPC_ENDPOINT=$METIS_RPC_URL \
 -e OPTIMISM_HEALTH_ENDPOINT=https://mainnet-sequencer.optimism.io/health \
 -e OPTIMISM_RPC_ENDPOINT=$OPTIMISM_RPC_URL \
 -e SCROLL_RPC_ENDPOINT=$SCROLL_RPC_URL \
 -e SONEIUM_RPC_ENDPOINT=$SONEIUM_RPC_URL \
 -e STARKWARE_RPC_ENDPOINT=$STARKNET_RPC_URL \
 -e UNICHAIN_RPC_ENDPOINT=$UNICHAIN_RPC_URL \
 -e XLAYER_RPC_ENDPOINT=$XLAYER_RPC_URL \
 -e TIMEOUT=30000 \
 -e CACHE_ENABLED=false \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=viewFunction \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=layer2-sequencer-health \
 -e RETRY=1 \
 -e DEBUG_ENDPOINTS=true \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="layer2-sequencer-health-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/layer2-sequencer-health-adapter:$1
