#!/bin/bash

# Source configuration files with absolute paths to ensure they work regardless of where the script is called from
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

source "${repo_root}/api_keys"
source "${repo_root}/misc_vars"
docker run \
 --name lido-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.219 \
 -p 1219:1219 \
 -e EA_PORT=1219 \
 -e POLYGON_RPC_URL=$POLYGON_RPC_URL \
 -e MATIC_RPC_URL=$MATIC_RPC_URL \
 -e TIMEOUT=30000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=lido \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=lido \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="lido-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/lido-adapter:$1
