#!/bin/bash

# ea-name: nav-fund-services-redis
# endpoint: http://192.168.2.101:2101

source api_keys
source misc_vars

docker run \
 --name nav-fund-services-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.101 \
 -p 2101:2101 \
 -e EA_PORT=2101 \
 -e TIMEOUT=30000 \
 -e API_ENDPOINT=https://api.navfundservices.com \
 -e API_KEY_220980=$NAV_FUND_SERVICES_API_KEY \
 -e SECRET_KEY_220980=$NAV_FUND_SERVICES_SECRET_KEY \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=nav-fund-services \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_MIN_AGE=120000 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=false \
 -e WS_ENABLED=false \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e RETRY=1 \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=nav-fund-services \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="nav-fund-services-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/nav-fund-services-adapter:$1
