#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name ncfx-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.163 \
 -p 1163:1163 \
 -e EA_PORT=1163 \
 -e WS_ENABLED=true \
 -e TIMEOUT=30000 \
 -e API_USERNAME=$NCFX_API_USERNAME \
 -e API_PASSWORD=$NCFX_API_PASSWORD \
 -e FOREX_WS_USERNAME=$NCFX_FOREX_WS_USERNAME \
 -e FOREX_WS_PASSWORD=$NCFX_FOREX_WS_PASSWORD \
 -e WS_API_ENDPOINT=$NCFX_WS_API_ENDPOINT \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=ncfx \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=ncfx \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="ncfx-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/ncfx-adapter:$1
 
