#!/bin/bash

# ea-name: nomia2-redis
# endpoint: http://192.168.2.100:2100

source api_keys
source misc_vars

docker run \
 --name nomia2-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.100 \
 -p 2100:2100 \
 -e EA_PORT=2100 \
 -e TIMEOUT=30000 \
 -e API_KEY=$NOMIA2_API_KEY \
 -e API_ENDPOINT=$NOMIA2_API_ENDPOINT \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=local \
 -e CACHE_MIN_AGE=120000 \
 -e CACHE_MAX_AGE=180000 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=false \
 -e WS_ENABLED=false \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=debug \
 -e DEBUG=true \
 -e RETRY=1 \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=nomia2 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="nomia2-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/nomia2-adapter:$1
