#!/bin/bash

source api_keys
source misc_vars

docker run \
--name nomics-redis \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.111 \
-p 1111:1111 \
-e EA_PORT=1111 \
-e TIMEOUT=30000 \
-e API_KEY=$NOMICS_API_KEY \
-e CACHE_ENABLED=true \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=nomics \
-e CACHE_KEY_IGNORED_PROPS=meta \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e RATE_LIMIT_ENABLED=true \
-e WARMUP_ENABLED=true \
-e RATE_LIMIT_API_PROVIDER=nomics \
-e RATE_LIMIT_API_TIER=$NOMICS_SUB_HTTP \
-e REQUEST_COALESCING_ENABLED=true \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e WARMUP_UNHEALTHY_THRESHOLD=3 \
-e WARMUP_SUBSCRIPTION_TTL=3600000 \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=true \
-e METRICS_NAME=nomics \
-d public.ecr.aws/chainlink/adapters/nomics-adapter:$1
