#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name oanda-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.247 \
 -p 2247:2247 \
 -e EA_PORT=2247 \
 -e TIMEOUT=60000 \
 -e API_KEY=$OANDA_API_KEY \
 -e API_ACCOUNT_ID=$OANDA_API_ACCOUNT_ID \
 -e API_ENDPOINT=$OANDA_API_ENDPOINT \
 -e INSTRUMENTS_API_ENDPOINT=$OANDA_INSTRUMENTS_API_ENDPOINT \
 -e SSE_API_KEY=$OANDA_SSE_API_KEY \
 -e SSE_API_ENDPOINT=$OANDA_SSE_API_ENDPOINT \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=oanda \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e RATE_LIMIT_API_PROVIDER=oanda \
 -e RATE_LIMIT_API_TIER=$OANDA_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=oanda \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="oanda-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/oanda-adapter:$1
