#!/bin/bash

# ea-name: por-address-list-redis
# endpoint: http://192.168.1.253:2253

source api_keys
source misc_vars

docker run \
 --name por-address-list-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.253 \
 -p 2253:2253 \
 -e EA_PORT=2253 \
 -e RPC_URL=$ETHEREUM_RPC_URL \
 -e ARBITRUM_RPC_URL=$ARBITRUM_RPC_URL \
 -e ARBITRUM_RPC_CHAIN_ID=$ARBITRUM_RPC_CHAIN_ID \
 -e ARBITRUM_CHAIN_ID=$ARBITRUM_CHAIN_ID \
 -e BASE_RPC_URL=$BASE_RPC_URL \
 -e BASE_RPC_CHAIN_ID=$BASE_CHAIN_ID \
 -e BSC_RPC_URL=$BSC_RPC_URL \
 -e BSC_RPC_CHAIN_ID=$BSC_CHAIN_ID \
 -e BSC_CHAIN_ID=$BSC_CHAIN_ID \
 -e ETHEREUEM_RPC_URL=$ETHEREUM_RPC_URL \
 -e ETHEREUEM_RPC_CHAIN_ID=$ETHEREUEM_CHAIN_ID \
 -e POLYGON_RPC_URL=$POLYGON_RPC_URL \
 -e POLYGON_RPC_CHAIN_ID=$POLYGON_CHAIN_ID \
 -e POLYGON_CHAIN_ID=$POLYGON_CHAIN_ID \
 -e CHAIN_ID=1 \
 -e TIMEOUT=60000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=por-address-list \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=por-address-list \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="por-address-list-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/por-address-list-adapter:$1
