#!/bin/bash

# ea-name: proof-of-reserves-v2-redis
# endpoint: http://192.168.2.116:2116

source api_keys
source misc_vars

docker run \
 --name proof-of-reserves-v2-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.116 \
 -p 2116:2116 \
 -e EA_PORT=2116 \
 -e TIMEOUT=60000 \
 -e API_TIMEOUT=30000 \
 -e CACHE_PREFIX=proof-of-reserves-v2-mercury \
 -e TOKEN_BALANCE_URL=http://192.168.2.59:2059 \
 -e GENERIC_API_URL=http://192.168.2.107:2107 \
 -e VIEW_FUNCTION_MULTI_CHAIN_URL=http://192.168.2.35:2035 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=proof-of-reserves-v2-mercury \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=proof-of-reserves-v2 \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="proof-of-reserves-v2-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/proof-of-reserves-v2-adapter:$1
