#!/bin/bash

# ea-name: securitize-redis
# endpoint: http://192.168.2.79:2079

source api_keys
source misc_vars

docker run \
 --name securitize-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.79 \
 -p 2079:2079 \
 -e EA_PORT=2079 \
 -e TIMEOUT=60000 \
 -e API_KEY=$SECURITIZE_API_KEY \
 -e VBILL_PUBKEYS=$SECURITIZE_VBILL_PUBKEYS \
 -e BUIDL_PUBKEYS=$SECURITIZE_BUIDL_PUBKEYS \
 -e ACRED_PUBKEYS=$SECURITIZE_ACRED_PUBKEYS \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=securitize \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e RATE_LIMIT_API_PROVIDER=securitize \
 -e RATE_LIMIT_API_TIER=$SECURITIZE_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=securitize \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="securitize-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/securitize-adapter:$1
