#!/bin/bash

source ../api_keys
source ../misc_vars

docker run \
--name setToken-index--multi-matic \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.212 \
-p 1212:1212 \
-e EA_PORT=1212 \
-e TIINGO_ADAPTER_URL=http://192.168.1.134:1134 \
-e COINPAPRIKA_ADAPTER_URL=http://192.168.1.116:1116 \
-e COINAPI_ADAPTER_URL=http://192.168.1.112:1112 \
-e CRYPTOCOMPARE_ADAPTER_URL=http://192.168.1.114:1114 \
-e NOMICS_ADAPTER_URL=http://192.168.1.111:1111 \
-e COINMARKETCAP_ADAPTER_URL=http://192.168.1.115:1115 \
-e TIINGO_ADAPTER_URL=http://192.168.1.134:1134 \
-e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
-e POLYGON_RPC_URL=$POLYGON_RPC_URL \
-e MATIC_RPC_URL=$MATIC_RPC_URL \
-e TIMEOUT=30000 \
-e CACHE_ENABLED=true \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=setTokenIndex-multi-matic \
-e CACHE_KEY_IGNORED_PROPS=meta \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e REQUEST_COALESCING_ENABLED=true \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=true \
-e METRICS_NAME=setIndex-matic \
-d public.ecr.aws/chainlink/adapters/set-token-index-adapter:$1
