#!/bin/bash

# Source configuration files with absolute paths to ensure they work regardless of where the script is called from
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

source "${repo_root}/api_keys"
source "${repo_root}/misc_vars"
docker run \
 --name setToken-index--multi-matic \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.212 \
 -p 1212:1212 \
 -e EA_PORT=1212 \
 -e COINAPI_ADAPTER_URL=http://192.168.1.112:1112 \
 -e COINGECKO_ADAPTER_URL=http://192.168.1.113:1113 \
 -e COINMETRICS_ADAPTER_URL=http://192.168.1.164:1164 \
 -e COINMARKETCAP_ADAPTER_URL=http://192.168.1.115:1115 \
 -e COINPAPRIKA_ADAPTER_URL=http://192.168.1.116:1116 \
 -e CRYPTOCOMPARE_ADAPTER_URL=http://192.168.1.114:1114 \
 -e NCFX_ADAPTER_URL=http://192.168.1.163:1163 \
 -e NOMICS_ADAPTER_URL=http://192.168.1.111:1111 \
 -e TIINGO_ADAPTER_URL=http://192.168.1.134:1134 \
 -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
 -e POLYGON_RPC_URL=$POLYGON_RPC_URL \
 -e MATIC_RPC_URL=$MATIC_RPC_URL \
 -e TIMEOUT=30000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=setTokenIndex-multi-matic \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_REDIS_TIMEOUT=30000 \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=setIndex-matic \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="set-token-index-multi--matic-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/set-token-index-adapter:$1
