#!/bin/bash

# ea-name: tenbin-redis
# endpoint: http://192.168.1.124:2124

source api_keys
source misc_vars

docker run \
  --name tenbin-redis \
  --restart=unless-stopped \
  --net eas-net \
  --link redis-cache \
  --ip 192.168.1.124 \
  -p 2124:2124 \
  -e EA_PORT=2124 \
  -e API_KEY=$TENBIN_API_KEY \
  -e TIMEOUT=30000 \
  -e CACHE_ENABLED=true \
  -e CACHE_TYPE=redis \
  -e CACHE_KEY_GROUP=tenbin \
  -e CACHE_REDIS_HOST="192.168.1.1" \
  -e CACHE_REDIS_PORT=6379 \
  -e CACHE_REDIS_TIMEOUT=10000 \
  -e RATE_LIMIT_ENABLED=true \
  -e WARMUP_ENABLED=true \
  -e RATE_LIMIT_API_PROVIDER=tenbin \
  -e RATE_LIMIT_API_TIER=$TENBIN_SUB_HTTP \
  -e REQUEST_COALESCING_ENABLED=true \
  -e REQUEST_COALESCING_INTERVAL=100 \
  -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
  -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
  -e REQUEST_COALESCING_ENTROPY_MAX=0 \
  -e LOG_LEVEL=info \
  -e DEBUG=false \
  -e API_VERBOSE=false \
  -e EXPERIMENTAL_METRICS_ENABLED=true \
  -e METRICS_NAME=tenbin \
  -e RETRY=1 \
  -l prometheus-scrape.enabled=true \
  -l prometheus-scrape.job_name="tenbin-redis" \
  -l prometheus-scrape.port=9080 \
  -l prometheus-scrape.metrics_path="/metrics" \
  -d public.ecr.aws/chainlink/adapters/tenbin-adapter:$1
