#!/bin/bash

source ../api_keys
source ../misc_vars

docker run \
--name tiingo-redis \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.134 \
-p 1134:1134 \
-e EA_PORT=1134 \
-e API_KEY=$TIINGO_API_KEY \
-e WS_ENABLED=true \
-e CACHE_ENABLED=true \
-e CACHE_MAX_AGE=20000 \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=tiingo \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e REQUEST_COALESCING_ENABLED=true \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e EXPERIMENTAL_RATE_LIMIT_ENABLED=false \
-e EXPERIMENTAL_WARMUP_ENABLED=false \
-e RATE_LIMIT_API_PROVIDER=tiingo \
-e RATE_LIMIT_API_TIER=commercial \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=false \
-e METRICS_NAME=tiingo \
-d public.ecr.aws/chainlink/adapters/tiingo-adapter:$1
