#!/bin/bash

# ea-name: tiingo-sol-redis
# endpoint: http://192.168.1.165:1165

source api_keys
source misc_vars

docker run \
 --name tiingo-sol-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.165 \
 -p 1165:1165 \
 -e EA_PORT=1165 \
 -e API_KEY=$TIINGO_API_KEY \
 -e WS_ENABLED=true \
 -e CACHE_ENABLED=true \
 -e CACHE_MAX_AGE=20000 \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=tiingo-sol \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_MIN_AGE=60000 \
 -e CACHE_MAX_AGE=120000 \
 -e RATE_LIMIT_ENABLED=false \
 -e WARMUP_ENABLED=false \
 -e RATE_LIMIT_API_PROVIDER=tiingo \
 -e RATE_LIMIT_API_TIER=$TIINGO_SUB_HTTP \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e WS_ENABLED=true \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=tiingo \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="tiingo-sol-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/tiingo-adapter:$1
