#!/bin/bash

# ea-name: tokenized-equity-redis
# endpoint: http://192.168.2.109:2109

source api_keys
source misc_vars

docker run \
 --name tokenized-equity-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.109 \
 -p 2109:2109 \
 -e EA_PORT=2109 \
 -e TIMEOUT=30000 \
 -e TRADING_HOURS_ADAPTER_URL=http://192.168.2.51:2051 \
 -e DATA_ENGINE_EA_URL=http://192.168.2.88:2088 \
 -e DATA_ENGINE_ADAPTER_URL=http://192.168.2.88:2088 \
 -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=local \
 -e CACHE_MIN_AGE=120000 \
 -e CACHE_MAX_AGE=180000 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=false \
 -e WS_ENABLED=false \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=debug \
 -e DEBUG=true \
 -e RETRY=1 \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=tokenized-equity \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="tokenized-equity-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/tokenized-equity-adapter:$1
