#!/bin/bash

# ea-name: tradingeconomics-redis
# endpoint: http://192.168.1.216:1216

source api_keys
source misc_vars

docker run \
 --name tradingeconomics-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.216 \
 -p 1216:1216 \
 -e EA_PORT=1216 \
 -e WS_ENABLED=true \
 -e TIMEOUT=30000 \
 -e API_URL=$TRADINGECONOMICS_API_URL \
 -e API_CLIENT_KEY=$TRADINGECONOMICS_API_CLIENT_KEY \
 -e API_CLIENT_SECRET=$TRADINGECONOMICS_API_CLIENT_SECRET \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=tradingeconomics \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e WARMUP_ENABLED=true \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=tradingeconomics \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="tradingeconomics-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/tradingeconomics-adapter:$1
