#!/bin/bash

source api_keys
source misc_vars

docker run \
--name tradermade-redis \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.209 \
-p 1209:1209 \
-e EA_PORT=1209 \
-e API_KEY=$TRADERMADE_API_KEY \
-e CACHE_ENABLED=true \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=tradermade \
-e CACHE_KEY_IGNORED_PROPS=meta \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e REQUEST_COALESCING_ENABLED=true \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=true \
-e METRICS_NAME=tradermade \
-d public.ecr.aws/chainlink/adapters/tradermade-adapter:$1
