#!/bin/bash

source api_keys
source misc_vars

docker run \
--name viewFunction-redis \
--restart=unless-stopped \
--net eas-net \
--link redis-cache \
--ip 192.168.1.211 \
-p 1211:1211 \
-e EA_PORT=1211 \
-e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
-e TIMEOUT=30000 \
-e CACHE_ENABLED=true \
-e CACHE_TYPE=redis \
-e CACHE_KEY_GROUP=viewFunction \
-e CACHE_KEY_IGNORED_PROPS=meta \
-e CACHE_REDIS_HOST="192.168.1.1" \
-e CACHE_REDIS_PORT=6379 \
-e REQUEST_COALESCING_ENABLED=true \
-e REQUEST_COALESCING_INTERVAL=100 \
-e REQUEST_COALESCING_INTERVAL_MAX=1000 \
-e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
-e REQUEST_COALESCING_ENTROPY_MAX=0 \
-e LOG_LEVEL=info \
-e DEBUG=false \
-e API_VERBOSE=false \
-e EXPERIMENTAL_METRICS_ENABLED=true \
-e METRICS_NAME=view-function \
-d public.ecr.aws/chainlink/adapters/view-function-adapter:$1
