#!/bin/bash

# ea-name: wintermute-redis
# endpoint: http://192.168.2.91:2091

source api_keys
source misc_vars

docker run \
 --name wintermute-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.2.91 \
 -p 2091:2091 \
 -e EA_PORT=2091 \
 -e TIMEOUT=60000 \
 -e API_KEY=$WINTERMUTE_API_KEY \
 -e WS_API_ENDPOINT=$WINTERMUTE_WS_API_ENDPOINT \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=wintermute \
 -e CACHE_KEY_IGNORED_PROPS=meta \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e RATE_LIMIT_ENABLED=true \
 -e CACHE_MIN_AGE=120000 \
 -e CACHE_MAX_AGE=180000 \
 -e REQUEST_COALESCING_ENABLED=true \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e WS_ENABLED=true \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=wintermute \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="wintermute-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/wintermute-adapter:$1
