#!/bin/bash

source api_keys
source misc_vars

docker run \
 --name xsushiPrice-redis \
 --restart=unless-stopped \
 --net eas-net \
 --link redis-cache \
 --ip 192.168.1.214 \
 -p 1214:1214 \
 -e EA_PORT=1214 \
 -e TIINGO_ADAPTER_URL=http://192.168.1.134:1134 \
 -e COINPAPRIKA_ADAPTER_URL=http://192.168.1.116:1116 \
 -e COINAPI_ADAPTER_URL=http://192.168.1.112:1112 \
 -e CRYPTOCOMPARE_ADAPTER_URL=http://192.168.1.114:1114 \
 -e NOMICS_ADAPTER_URL=http://192.168.1.111:1111 \
 -e COINMARKETCAP_ADAPTER_URL=http://192.168.1.115:1115 \
 -e TIINGO_ADAPTER_URL=http://192.168.1.132:1132 \
 -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
 -e XSUSHI_ADDRESS=0x8798249c2E607446EfB7Ad49eC89dD1865Ff4272 \
 -e TIMEOUT=30000 \
 -e CACHE_ENABLED=true \
 -e CACHE_TYPE=redis \
 -e CACHE_KEY_GROUP=xsushiPrice \
 -e CACHE_REDIS_HOST="192.168.1.1" \
 -e CACHE_REDIS_PORT=6379 \
 -e CACHE_REDIS_TIMEOUT=30000 \
 -e REQUEST_COALESCING_ENABLED=false \
 -e REQUEST_COALESCING_INTERVAL=100 \
 -e REQUEST_COALESCING_INTERVAL_MAX=1000 \
 -e REQUEST_COALESCING_INTERVAL_COEFFICIENT=2 \
 -e REQUEST_COALESCING_ENTROPY_MAX=0 \
 -e LOG_LEVEL=info \
 -e DEBUG=false \
 -e API_VERBOSE=false \
 -e EXPERIMENTAL_METRICS_ENABLED=true \
 -e METRICS_NAME=xsushiPrice \
 -e RETRY=1 \
 -l prometheus-scrape.enabled=true \
 -l prometheus-scrape.job_name="sushi-redis" \
 -l prometheus-scrape.port=9080 \
 -l prometheus-scrape.metrics_path="/metrics" \
 -d public.ecr.aws/chainlink/adapters/xsushi-price-adapter:$1
